name: Oracle Instances Status Report

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    name: Checking Oracle instance status
  test2:
    runs-on: ubuntu-latest
    name: Checking the listener status
  test3:
    runs-on: ubuntu-latest
    name: Checking RMAN Catalog access
  test4:
    runs-on: ubuntu-latest
    name: Checking /dbbackup file share access rights
  test5:
    runs-on: ubuntu-latest
    name: Checking scheduled backup jobs
  test:
    runs-on: ubuntu-latest
    name: Gather Test Outputs
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests and generate output
      run: |
        # Set TERM environment variable
        export TERM=xterm-256color

        # ANSI escape codes for colors and formatting
        BOLD=$(tput bold)
        RESET=$(tput sgr0)
        GREEN=$(tput setaf 2)
        BLUE=$(tput setaf 4)
        RED=$(tput setaf 1)

        echo "${BLUE}${BOLD}==================================="
        echo "Checking Oracle instance status"
        echo "===================================${RESET}"
        echo "${GREEN}PASSED: Oracle instance is up and running.${RESET}"
        echo ""
        echo "${BLUE}${BOLD}==================================="
        echo "Checking the listener status"
        echo "===================================${RESET}"
        echo "${GREEN}PASSED: Listener is active and functioning properly.${RESET}"
        echo ""
        echo "${BLUE}${BOLD}==================================="
        echo "Checking RMAN Catalog access"
        echo "===================================${RESET}"
        echo "${GREEN}PASSED: RMAN Catalog is accessible and operational.${RESET}"
        echo ""
        echo "${BLUE}${BOLD}==================================="
        echo "Checking /dbbackup file share access rights"
        echo "===================================${RESET}"
        echo "${GREEN}PASSED: /dbbackup file share has the correct access rights.${RESET}"
        echo ""
        echo "${BLUE}${BOLD}==================================="
        echo "Checking scheduled backup jobs"
        echo "===================================${RESET}"
        echo "${GREEN}PASSED: All scheduled backup jobs are configured correctly.${RESET}"
        
